version: 2.1
orbs:
  git-shallow-clone: guitarrapc/git-shallow-clone@2.0.3
jobs:
  build:
    machine:
      image: 'ubuntu-2004:202010-01'
    steps:
      - git-shallow-clone/checkout
      - run:
          name: Checkout submodules
          command: |
            git submodule sync
            git submodule update --init --recursive --depth=1
      - run:
          name: Install dependencies
          command: |
            sudo dpkg --add-architecture i386
            
            sudo apt-get update
            sudo apt-get install --no-install-recommends -y devscripts equivs debhelper libdistro-info-perl libfreetype6-dev:i386
            sudo mk-build-deps -i -r -t "apt-get --no-install-recommends -y" debian/control
      - run:
          name: Build DSCs
          no_output_timeout: 30m
          command: |
            tools/debian/make-deb --dsc
      - run:
          name: Move DSCs
          command: mkdir source && mv ../*~$(lsb_release -cs).* source
      - run:
          name: Build DEBs
          no_output_timeout: 30m
          command: |
            tools/debian/make-deb
      - run:
          name: Move DEBs
          command: mkdir dist && mv ../*.deb dist
      - store_artifacts:
          path: dist/
          destination: debs
      - store_artifacts:
          path: source/
          destination: source
