version: 2.1
orbs:
  git-shallow-clone: guitarrapc/git-shallow-clone@2.0.3
jobs:
  build:
    machine:
      image: 'ubuntu-1604:202004-01'
    steps:
      - git-shallow-clone/checkout
      - run:
          name: Checkout submodules
          command: |
            git submodule sync
            git submodule update --init --recursive --depth=1
      - run:
          name: Install dependencies
          command: |
            # keys
            wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | sudo apt-key add -
            wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
            
            # repos
            sudo apt-add-repository 'deb https://apt.kitware.com/ubuntu/ xenial main'
            sudo apt-add-repository 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-9 main'
            sudo add-apt-repository ppa:deadsnakes/ppa
            
            sudo dpkg --add-architecture i386
            
            sudo apt-get update
            sudo apt-get upgrade -y cmake
            sudo apt-get install --no-install-recommends -y devscripts equivs debhelper libdistro-info-perl python3.8 clang-9 libfreetype6-dev:i386
            sudo mk-build-deps -i -r -t "apt-get --no-install-recommends -y" debian/control
            
            sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.8 1
            sudo update-alternatives --auto python3
      - run:
          name: Build DSCs
          no_output_timeout: 30m
          command: |
            export DEB_DISTRO=$(lsb_release -cs)
            tools/makedeb --dsc
      - run:
          name: Move DSCs
          command: mkdir source && mv ../*~$(lsb_release -cs).* source
      - run:
          name: Build DEBs
          no_output_timeout: 30m
          command: |
            export DEB_DISTRO=$(lsb_release -cs)
            tools/makedeb
      - run:
          name: Move DEBs
          command: mkdir dist && mv ../*.deb dist
      - store_artifacts:
          path: dist/
          destination: debs
      - store_artifacts:
          path: source/
          destination: source
